# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/shadow_project_dma/shadow_dma_1/shadow_dma_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
# IP: The module: 'design_1_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/shadow_project_dma/shadow_dma_1/shadow_dma_1.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/shadow_project_dma/shadow_dma_1/shadow_dma_1.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/shadow_project_dma/shadow_dma_1/shadow_dma_1.srcs/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
# IP: The module: 'design_1_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/shadow_project_dma/shadow_dma_1/shadow_dma_1.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/shadow_project_dma/shadow_dma_1/shadow_dma_1.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
